[package]
name = "quickpath"
version = "1.0.2"
edition = "2024"
description = "专为 Windows 10/11 打造的现代 Fluent 风格文件对话框智能路径跟随与快速跳转利器"
authors = ["衢州御风科技有限公司 <https://qp.yftec.top>"]
homepage = "https://qp.yftec.top"
repository = "https://github.com/clhome/QuickPath"
license = "GPL-3.0"
keywords = ["windows", "file-dialog", "quick-access", "fluent-design"]
categories = ["command-line-utilities", "os::windows-apis"]

[dependencies]
directories = "6.0.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "0.8"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Input_Ime", "Win32_UI_Accessibility", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_Graphics_Gdi", "Win32_Graphics_GdiPlus", "Win32_Graphics_Dwm", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Ole", "Win32_System_Threading", "Win32_System_ProcessStatus", "Win32_System_DataExchange", "Win32_System_LibraryLoader", "Win32_Security", "Win32_UI_HiDpi", "Win32_System_Registry", "Win32_System_Memory", "Win32_System_Variant", "Win32_Globalization"] }


[build-dependencies]
embed-resource = "3.0.11"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true



